### ISSUE TITLE
Feature Request: Allow mounting configmaps/secrets into Vault container

### ISSUE THREAD

**Issue by arnarg** [kubevault/issues#60]
When using PostgreSQL RDS for Secrets or Storage engine you need to get CA root certificate [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html). It's not possible to mount it into the Vault container to reference with [sslrootcert](https://www.postgresql.org/docs/8.4/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT) in the postgresql connection string.

Maybe it should be possible to specify this in `.spec.podTemplate` for `VaultServer`.

**Comment by tamalsaha** [comment]
```
	// DataSources is a list of Configmaps/Secrets in the same namespace as the VaultServer
	// object, which shall be mounted into the VaultServer Pods.
	// The Secrets are mounted into /etc/vault/data/<name>.
	DataSources []core.VolumeSource `json:"dataSource,omitempty"`
```

**Comment by arnarg** [comment]
I don't understand your response, are you saying this is already available?

**Comment by tamalsaha** [comment]
@kamolhasan has started working on this feature. We are planning to add the `DataSources` field which will allow you to mount configmaps and secrets or any volume into a Vault server pod.

**Comment by arnarg** [comment]
ok thanks! :)

**Comment by arnarg** [comment]
Seems that this functionality has been added. Should I close this issue?

**Comment by tamalsaha** [comment]
We are going to close the issue once the release is out.

**Comment by tamalsaha** [comment]
This is released with the https://github.com/kubevault/operator/releases/tag/v0.3.0 release.
