### ISSUE TITLE
Installation instructions for existing Vault instance

### ISSUE THREAD

**Issue by thecodejunkie** [kubevault/issues#78]
Hi

I want to try out the Vault CSI driver together with an existing (not deployed on Kubernetes) Vault instance. Is it enough to follow these instructions https://github.com/kubevault/docs/blob/master/docs/guides/secret-engines/kv/csi-driver.md#csi-driver to make it work? I.e., is the Vault Operator not required if we already have an existing Vault instance running elsewhere? Is Kubernetes auth configuration + AppBidning + StorageClass + PVC enough to get it up and to run in my cluster?

**Comment by thecodejunkie** [comment]
One more thing, I have no interesting in managing the existing Vault instance though Kubernetes resources. I.e., I won't be managing policies, etc. through Kubernetes. I want to be able to inject secrets, from said existing Vault instance, into my pods

**Comment by tamalsaha** [comment]
You can do that. See the document here: https://kubevault.com/docs/v0.3.0/guides/platforms/external-vault/

For injecting secrets, see the CSI driver docs in the secret engine section. Example: AWS docs https://kubevault.com/docs/v0.3.0/guides/secret-engines/aws/csi-driver/
