### ISSUE TITLE
Vault operator helm template for the cleaner job is missing namespace support

### ISSUE THREAD

**Issue by thecodejunkie** [kubevault/issues#80]
Hi

It appears that https://github.com/kubevault/operator/blob/master/charts/vault-operator/templates/cleaner.yaml does not support passing in a namespace, it is missing the following in the chart definition. This is a tiny, yet rather annoying bug that hopefully should be able to be fixed easy. 

```
namespace: {{ .Release.Namespace }}
```

pinging @tamalsaha since I saw you had touched those files recently. Would it be possible to get a v0.2.1 released with this fix?

Thanks!

**Comment by tamalsaha** [comment]
Yeah. I believe this is one of those changes from helm 2 to 3. If you are interested, please file a pull request.
